### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by suatsuphi** [ubports/sqlite-icu-extension#1]
Hi,

I use sqlite on asp.net core. but I have problem on non-ASCII characters. how can I add this c code ? I mean this splite-icu-extension

**Comment by Flohack74** [comment]
Are you sure you are in the right repo?

**Comment by Flohack74** [comment]
Ah ok you mean how to incorporate this in a .NET project? Well I guess we are not the right ones, but its not so straightforward, if you are using System.Data.SQLite library it ships a build of sqlite unmanaged lib. I guess that one would need to be replaced with one that you build on your own, adding that extension.
Sorry we cannot help for this, you have reached Ubuntu Touch, the alternative mobile operating system. And we dont to .NET at all ^^
